/*
Se crea triger que actualiza la tabla detalle_boleta (valor unitario y total) cuando se actualiza el valor unitario de un producto en la tabla PRODUCTO
*/ 
create or replace TRIGGER TRG_UPDATE 
BEFORE UPDATE OF VALOR_UNITARIO ON PRODUCTO
FOR EACH ROW
DECLARE
V_VENTA_AGNO_ANTERIOR_10P NUMBER; --VARIABLE PARA ALMACENAR EL 10% DE LA VENTA DEL AÑO ANTERIOR
BEGIN
  V_VENTA_AGNO_ANTERIOR_10P:=ROUND(PKG_SUMATIVA_SEMANA8.F_GET_VENTAS_ANUAL(TO_NUMBER(to_char(sysdate-365, 'YYYY')))*0.1,0);--10% del promedio de todas las ventas del año anerior
  IF :new.VALOR_UNITARIO > V_VENTA_AGNO_ANTERIOR_10P THEN -- SOLO SI EL VALOR UNITARIO NUEVO ES MAYOR AL 10% DE LA VENTA PROMEDIO DEL AÑO ANTERIOR
    UPDATE DETALLE_BOLETA SET VUNITARIO = :new.VALOR_UNITARIO, VALOR_TOTAL = :new.VALOR_UNITARIO * CANTIDAD WHERE COD_PRODUCTO = :old.COD_PRODUCTO; -- SE ACTUALIZA LA TABLA DETALLE BOLETA CON EL NUEVO VALOR UNITARIO Y SE RECALCULA EL VALOR TOTAL
  END IF;
END;F;
END;