VARIABLE B_PERIODO VARCHAR(7); /* INGRESAR EN FORMATO MM/YYYY */

DECLARE
    V_CONTADOR INT:=0;
    V_REGISTROS_CLIENTES INT:=0;
    V_PUNTAJE DETALLE_DE_CLIENTES.PUNTAJE%TYPE;
    V_CORREO_CORP DETALLE_DE_CLIENTES.CORREO_CORP%TYPE;
    V_ANNO_VIG TRAMO_EDAD.ANNO_VIG%TYPE;
    V_EDAD INT;

    CURSOR C_CLIENTES IS
    SELECT 
        ID_CLI,
        NUMRUN_CLI,
        APPATERNO_CLI,
        APMATERNO_CLI,
        PNOMBRE_CLI,
        RENTA,
        FECHA_NAC_CLI,
        ID_COMUNA,
        ID_TIPO_CLI
        FROM CLIENTE;
BEGIN

    EXECUTE IMMEDIATE 'TRUNCATE TABLE DETALLE_DE_CLIENTES';
    SELECT COUNT(1) INTO V_REGISTROS_CLIENTES FROM CLIENTE; /* SE OBTIENE EL TOTAL DE REGISTROS DE LA TABLA DE CLIENTES QUE DEBEN SER PROCESADOS */
    DBMS_OUTPUT.put_line('PROCESANDO CLIENTES ...');
    FOR C in C_CLIENTES LOOP
        V_EDAD:=ROUND((SYSDATE-C.FECHA_NAC_CLI)/365);   /* SE CALCULA LA EDAD DEL CLIENTE */
        IF C.RENTA > 700000 AND C.ID_COMUNA NOT IN (85, 80, 84) THEN  /* SI LA RENTA ES SUPERIOR A 700 MIL Y VIVE EN LA REINA, LAS CONDES O VITACURA PUNTAJE ES 30% DE LA RENTA */
            V_PUNTAJE:= ROUND(C.RENTA*0.3);
        ELSIF C.ID_TIPO_CLI IN ('D','B') THEN           /* SI ES DEL TIPO VIP O EXTRANJERO EL PUNTAJE ES 30 POR LA EDAD */
            V_PUNTAJE:=30*V_EDAD;
        ELSE                                            /* SINO EL PUNTAJE SE CALCULA EN BASE AL TRAMO DE EDAD DEPENDIENDO DEL AGNO DEL PERIODO */
            V_ANNO_VIG:= TO_NUMBER(SUBSTR(TO_CHAR(:B_PERIODO),4));
            SELECT ROUND((PORCENTAJE/100)*C.RENTA) INTO V_PUNTAJE FROM TRAMO_EDAD WHERE ANNO_VIG = V_ANNO_VIG AND V_EDAD BETWEEN TRAMO_INF AND TRAMO_SUP;
        END IF;
        
        /* SE PROCEDE A SETEAR EL CORREO DEL CLIENTE Y A INSERTAR EL REGISTRO EN LA BASE DE DATOS */
        
        V_CORREO_CORP:=LOWER(C.APPATERNO_CLI) || V_EDAD || '*' || SUBSTR(C.PNOMBRE_CLI,0,1) || SUBSTR(TO_CHAR(C.FECHA_NAC_CLI),0,2) || SUBSTR(TO_CHAR(:B_PERIODO),0,2) || '@LogiCarg.cl';
        INSERT INTO DETALLE_DE_CLIENTES(IDC, RUT, CLIENTE, EDAD, PUNTAJE, CORREO_CORP, PERIODO) VALUES (C.ID_CLI,C.NUMRUN_CLI,INITCAP(C.APPATERNO_CLI) || ' ' || INITCAP(C.APMATERNO_CLI) || ' ' ||  INITCAP(C.PNOMBRE_CLI), V_EDAD, V_PUNTAJE, V_CORREO_CORP, :B_PERIODO);
        V_CONTADOR:=V_CONTADOR+1; /* SE AUMENTA EL CONTADOR DE REGISTROS PROCESADOS */
    END LOOP;
    IF V_REGISTROS_CLIENTES <> V_CONTADOR THEN      /* SE VALIDA QUE SE HAYAN PROCESADO TODOS LOS REGISTROS */
        DBMS_OUTPUT.put_line('SE PROCEDE AL ROLLBACK YA QUE NO SE PROCESARON TODOS LOS REGISTROS');
        ROLLBACK;
    END IF;    
    DBMS_OUTPUT.put_line('PROCESO FINALIZADO EXITOSAMENTE');
    DBMS_OUTPUT.put_line('SE PROCESARON: '|| V_CONTADOR || ' CLIENTES');
    COMMIT;
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE (SQLCODE || ' ' || SQLERRM);
    ROLLBACK;
END;